"""add last_reminder_sent_at to interviews

Revision ID: 245461404af3
Revises: 425ed1175f0f
Create Date: 2026-08-06 18:31:13.153033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245461404af3'
down_revision: Union[str, None] = '425ed1175f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('last_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'last_reminder_sent_at')
    # ### end Alembic commands ###
