"""add candidate delete cascade and audit threshold fields

Revision ID: 51054269292b
Revises: baf6114adfb2
Create Date: 2026-07-22 08:06:44.461094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51054269292b'
down_revision: Union[str, None] = 'baf6114adfb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
