"""add selfie_storage_path to candidates

Revision ID: 682145b287f7
Revises: 7bd4e43c4bd9
Create Date: 2026-08-08 21:37:32.970341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682145b287f7'
down_revision: Union[str, None] = '7bd4e43c4bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('selfie_storage_path', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'selfie_storage_path')
    # ### end Alembic commands ###
