"""add decision log and interview expiry

Revision ID: 7f260c6a957c
Revises: a35350ef87d5
Create Date: 2026-07-21 14:17:48.282860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f260c6a957c'
down_revision: Union[str, None] = 'a35350ef87d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('step_name', sa.String(length=128), nullable=False),
    sa.Column('step_type', sa.Enum('DETERMINISTIC', 'PROBABILISTIC', name='decision_step_type'), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_logs_entity_id'), 'decision_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_decision_logs_entity_type'), 'decision_logs', ['entity_type'], unique=False)
    op.add_column('interviews', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'expires_at')
    op.drop_index(op.f('ix_decision_logs_entity_type'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_entity_id'), table_name='decision_logs')
    op.drop_table('decision_logs')
    # ### end Alembic commands ###
