"""add contacted field to candidates

Revision ID: 9fabda6c6311
Revises: a260e20b414a
Create Date: 2026-08-21 12:45:44.275375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fabda6c6311'
down_revision: Union[str, None] = 'a260e20b414a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('contacted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'contacted')
    # ### end Alembic commands ###
