"""add ctc, notice period, experience fields to candidates

Revision ID: a260e20b414a
Revises: f705b8142d8d
Create Date: 2026-08-13 16:57:59.749640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a260e20b414a'
down_revision: Union[str, None] = 'f705b8142d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('current_ctc', sa.String(length=64), nullable=True))
    op.add_column('candidates', sa.Column('expected_ctc', sa.String(length=64), nullable=True))
    op.add_column('candidates', sa.Column('notice_period_days', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('total_years_experience', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'total_years_experience')
    op.drop_column('candidates', 'notice_period_days')
    op.drop_column('candidates', 'expected_ctc')
    op.drop_column('candidates', 'current_ctc')
    # ### end Alembic commands ###
